apiVersion: apps/v1
kind: Deployment
metadata:
  name: informix
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: informix
  template:
    metadata:
      labels:
        app: informix
    spec:
      securityContext:
        runAsUser: 200         # Gebruiker 'Yonis' heeft UID 300
        fsGroup: 200           # Groep 'Cursist' heeft GID 300
      containers:
        - name: informix
          image: ibmcom/informix-developer-database:{{DB_VERSION}}
          ports:
            - containerPort: 9088  # Poort voor Informix
            - containerPort: 9089  # Poort voor Informix
          volumeMounts:
            - mountPath: /opt/ibm/data
              name: informix-storage
          env:
            - name: LICENSE
              value: "accept"
            - name: INFORMIX_VERSION
              valueFrom:
                configMapKeyRef:
                  name: informix-config
                  key: INFORMIX_VERSION
          envFrom:
            - secretRef:
                name: informix-secret
      volumes:
        - name: informix-storage
          persistentVolumeClaim:
            claimName: informix-pvc
