apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: informix-pvc
  namespace: {{NAMESPACE}}
spec:
  storageClassName: "local-path" # Gebruik de lokale storageClass in k3s
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
