apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{NAMESPACE}}-pvc
  namespace: {{NAMESPACE}}
spec:
  storageClassName: "" # Gebruik de lokale storageClass in k3s
  volumeName: {{NAMESPACE}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
