apiVersion: v1
kind: Service
metadata:
  name: informix-service
  namespace: {{NAMESPACE}}
  labels:
    app: informix
spec:
  type: NodePort 
  selector:
    app: informix
  ports:
    - name: port-9088
      protocol: TCP
      port: 9088
      targetPort: 9088
      nodePort: {{NODE_PORT}}
    - name: port-9089
      protocol: TCP
      port: 9089
      targetPort: 9089
      nodePort: {{NODE_PORT_PLUS_ONE}}
