apiVersion: batch/v1
kind: Job
metadata:
  name: init-informix-permissions
  namespace: informix-v12
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0  # Run as root to set up the permissions
      containers:
        - name: init-permissions
          image: alpine:latest
          command:
            - "sh"
            - "-c"
            - |
              # Wachtwoord genereren
              password=$(openssl rand -base64 12)
              echo "Generated password for guest user: $password"
              
              # Maak de gebruiker aan
              useradd -m -u 1000 guest || true
              
              # Wachtwoord instellen voor de gebruiker
              echo "guest:$password" | chpasswd
              
              # Zorg ervoor dat de map voor guest bestaat
              mkdir -p /opt/ibm/data/guest || true
              chown -R guest:guest /opt/ibm/data/guest || true
              chmod -R 755 /opt/ibm/data/guest || true
          volumeMounts:
            - mountPath: /opt/ibm/data
              name: informix-storage  # Mounting the same volume as the Deployment
      volumes:
        - name: informix-storage
          persistentVolumeClaim:
            claimName: informix-pvc  # PVC that should be used for the volume
      restartPolicy: Never
  backoffLimit: 4
