apiVersion: batch/v1
kind: Job
metadata:
  name: init-informix-permissions
  namespace: informix-v12
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0  # Run as root to set up the permissions
      containers:
        - name: init-permissions
          image: alpine:latest
          command:
            - "sh"
            - "-c"
            - |
              # Install the required utilities
              apk update && apk add openssl shadow sudo

              # Generate a random password
              password=$(openssl rand -base64 12)
              echo "Generated password for guest user: \$password"
              
              # Create the guest user and set the password
              useradd -m -u 1000 guest || true
              echo "guest:\$password" | chpasswd
              
              # Create the directory and set ownership and permissions
              mkdir -p /opt/ibm/data/guest || true
              chown -R guest:guest /opt/ibm/data/guest || true
              chmod -R 755 /opt/ibm/data/guest || true
          volumeMounts:
            - mountPath: /opt/ibm/data
              name: informix-storage  # Mounting the same volume as the Deployment
      volumes:
        - name: informix-storage
          persistentVolumeClaim:
            claimName: informix-pvc  # PVC that should be used for the volume
      restartPolicy: Never
  backoffLimit: 4
