apiVersion: batch/v1
kind: Job
metadata:
  name: init-informix-permissions
  namespace: informix-v12
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0  # Run as root to set up the permissions
      containers:
        - name: init-permissions
          image: registry.access.redhat.com/ubi8/ubi
          command:
            - "sh"
            - "-c"
            - |
              # Create the 'informix' group and user with UID 200
              groupadd -g 200 informix || true
              useradd -u 200 -g informix -s /bin/bash informix || true
              # Create the 'user2' group and user with UID 201
              groupadd -g 201 user2 || true
              useradd -u 201 -g user2 -s /bin/bash user2 || true
              # Create directory for user2 if it doesn't exist
              mkdir -p /opt/ibm/data/user2 || true
              # Set ownership and permissions for directories
              chown -R informix:informix /opt/ibm/data || true
              chmod -R 755 /opt/ibm/data || true
              chmod 660 /opt/ibm/data/spaces/*.000 || true
              # Set ownership and permissions for the user2 directory
              chown -R user2:user2 /opt/ibm/data/user2 || true
              chmod -R 755 /opt/ibm/data/user2 || true
          volumeMounts:
            - mountPath: /opt/ibm/data
              name: informix-storage  # Mounting the same volume as the Deployment
      volumes:
        - name: informix-storage
          persistentVolumeClaim:
            claimName: informix-pvc  # PVC that should be used for the volume
      restartPolicy: Never
  backoffLimit: 4
