apiVersion: batch/v1
kind: Job
metadata:
  name: init-informix-permissions
  namespace: informix-v12
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0  # Run as root to set up the permissions
      containers:
        - name: init-permissions
          image: alpine
          command:
            - "sh"
            - "-c"
            - |
              # Create the user and group with UID 200 and GID 200
              addgroup -g 200 informix || true
              adduser -u 200 -G informix informix || true
              # Set the appropriate ownership and permissions
              chown -R informix:informix /opt/ibm/data || true
              chmod -R 755 /opt/ibm/data || true
              chmod 660 /opt/ibm/data/spaces/*.000 || true
          volumeMounts:
            - mountPath: /opt/ibm/data
              name: informix-storage  # Mounting the same volume as the Deployment
      volumes:
        - name: informix-storage
          persistentVolumeClaim:
            claimName: informix12-pvc  # PVC that should be used for the volume
      restartPolicy: Never
  backoffLimit: 4
