apiVersion: apps/v1
kind: Deployment
metadata:
  name: informix
  namespace: informixtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: informix
  template:
    metadata:
      labels:
        app: informix
    spec:
      securityContext:
        runAsUser: 200         # Gebruiker 'informix' heeft UID 200
        fsGroup: 200           # Zorg ervoor dat de groep ook toegang heeft
      initContainers:
        - name: init-onconfig
          image: alpine
          securityContext:
            runAsUser: 0       # Voer als root uit om bestandstoegang te garanderen
          command: ["sh", "-c", "sed -i 's/^usermapping off/usermapping basic/' /opt/ibm/config/onconfig"]
          volumeMounts:
            - mountPath: /opt/ibm/config
              name: informix-config
        - name: init-permissions
          image: alpine
          securityContext:
            runAsUser: 0
          command: ["sh", "-c", "addgroup -g 200 informix || true \
                         && adduser -u 200 -G informix informix || true \
                         && chown -R informix:informix /opt/ibm/data \
                         && chmod -R 755 /opt/ibm/data \
                         && chmod 660 /opt/ibm/data/spaces/*.000"]
          volumeMounts:
            - mountPath: /opt/ibm/data
              name: informix-storage
        - name: init-user-setup
          image: alpine
          securityContext:
            runAsUser: 0       # Zorg ervoor dat dit script rootrechten heeft
          command: ["sh", "-c", "/scripts/user-setup.sh"]
          volumeMounts:
            - mountPath: /scripts
              name: script-volume
      containers:
        - name: informix
          image: ibmcom/informix-developer-database:14.10.FC7W1DE
          ports:
            - containerPort: 9088  # Poort voor Informix
            - containerPort: 9089  # Poort voor Informix
          volumeMounts:
            - mountPath: /opt/ibm/data
              name: informix-storage
            - mountPath: /opt/ibm/config
              name: informix-config
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "onmode -ky && oninit"]  # Herstart Informix na wijzigingen
          env:
            - name: LICENSE
              value: "accept"
            - name: INFORMIX_VERSION
              valueFrom:
                configMapKeyRef:
                  name: informix-config
                  key: INFORMIX_VERSION
          envFrom:
            - secretRef:
                name: informix-secret
      volumes:
        - name: informix-storage
          persistentVolumeClaim:
            claimName: informixtest-pvc
        - name: script-volume
          configMap:
            name: informix-scripts
