apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: informix-pvc
  namespace: informixtest
spec:
  storageClassName: ""
  volumeName: informix-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
