apiVersion: apps/v1
kind: Deployment
metadata:
  name: informix
  namespace: informix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: informix
  template:
    metadata:
      labels:
        app: informix
    spec:
      securityContext:
        runAsUser: 300         # Gebruiker met UID 300
        fsGroup: 300           # Groep met GID 300
      initContainers:
        - name: init-permissions
          image: alpine
          securityContext:
            runAsUser: 0         # Init-container uitgevoerd als root
          command: ["sh", "-c", "addgroup -g 300 informix1 || true \
                         && adduser -u 300 -G informix1 informix1 || true \
                         && chown -R 300:300 /opt/ibm/data \
                         && chmod -R 777 /opt/ibm/data \
                         && chmod 660 /opt/ibm/data/spaces/*.000"]
          volumeMounts:
            - mountPath: /opt/ibm/data
              name: informix-storage
      containers:
        - name: informix
          securityContext:
            runAsUser: 300       # Container draait als UID 300
            fsGroup: 300         # Groep met GID 300
          image: ibmcom/informix-developer-database:14.10.FC7W1DE
          ports:
            - containerPort: 9088  # Poort voor Informix
            - containerPort: 9089  # Poort voor Informix
          volumeMounts:
            - mountPath: /opt/ibm/data
              name: informix-storage
          env:
            - name: LICENSE
              value: "accept"
            - name: INFORMIX_VERSION
              valueFrom:
                configMapKeyRef:
                  name: informix-config
                  key: INFORMIX_VERSION
          envFrom:
            - secretRef:
                name: informix-secret
      volumes:
        - name: informix-storage
          persistentVolumeClaim:
            claimName: informix-pvc
